apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  selector:
    matchLabels:
      app: db-noticias
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
      - name: db-noticias
        image: aluracursos/mysql-db:1
        ports:
        - containerPort: 3306
        envFrom:
            - configMapRef:
                  name: db-configmap
